Tuya2SNMP-MiboxerFUT037W DEFINITIONS ::= BEGIN

IMPORTS
	OBJECT-TYPE, NOTIFICATION-TYPE, Integer32
		FROM SNMPv2-SMI
	DisplayString, TruthValue
		FROM SNMPv2-TC
	tuyadevices, DeviceIndex
		FROM Tuya2SNMP;

miboxerFUT037W    OBJECT IDENTIFIER ::= { tuyadevices 101 }
dpUpdate          OBJECT IDENTIFIER ::= { miboxerFUT037W 2 }

-------------------------
-- Textual conventions --
-------------------------
 
WorkMode ::= TEXTUAL-CONVENTION
	DISPLAY-HINT   "d"
	STATUS         current
	DESCRIPTION    ""
	SYNTAX         INTEGER {
		white(0),
		colour(1),
		scene(2),
		music(3)
	}
	
-------------------------
-- Switches -------------
-------------------------

devicesTable OBJECT-TYPE
	SYNTAX SEQUENCE OF DeviceEntry
	ACCESS not-accessible
	STATUS mandatory
	DESCRIPTION ""
	::= { miboxerFUT037W 1 }
	
deviceEntry OBJECT-TYPE
	SYNTAX DeviceEntry
	ACCESS not-accessible
	STATUS mandatory
	DESCRIPTION ""
	INDEX { deviceIndex }
	::= { devicesTable 1 }
	
DeviceEntry ::= SEQUENCE {
	dpSwitch
		TruthValue,
	dpWorkmode
		WorkMode,
	dpBright
		INTEGER,
	dpTemp
		INTEGER,
	dpColour
		OCTET STRING,
	calcColourHue
		INTEGER,
	calcColourSaturation
		INTEGER,
	calcColourBrightness
		INTEGER
}

deviceIndex OBJECT-TYPE
	SYNTAX DeviceIndex
	ACCESS not-accessible
	STATUS mandatory
	DESCRIPTION ""
	::= { deviceEntry 0 }
   
dpSwitch OBJECT-TYPE
	SYNTAX TruthValue
	ACCESS read-write
	STATUS mandatory
	DESCRIPTION ""
	::= { deviceEntry 20 }
	
dpWorkmode OBJECT-TYPE
	SYNTAX WorkMode
	ACCESS read-write
	STATUS mandatory
	DESCRIPTION ""
	::= { deviceEntry 21 }
	
dpBright OBJECT-TYPE
	SYNTAX INTEGER (10..1000)
	ACCESS read-write
	STATUS mandatory
	DESCRIPTION ""
	::= { deviceEntry 22 }
	
dpTemp OBJECT-TYPE
	SYNTAX INTEGER (0..1000)
	ACCESS read-write
	STATUS mandatory
	DESCRIPTION ""
	::= { deviceEntry 23 }
	
dpColour OBJECT-TYPE
	SYNTAX OCTET STRING
	ACCESS read-write
	STATUS mandatory
	DESCRIPTION ""
	::= { deviceEntry 24 }
	
calcColourHue OBJECT-TYPE
	SYNTAX INTEGER (0..1000)
	ACCESS read-write
	STATUS mandatory
	DESCRIPTION ""
	::= { deviceEntry 10001 }
	
calcColourSaturation OBJECT-TYPE
	SYNTAX INTEGER (0..1000)
	ACCESS read-write
	STATUS mandatory
	DESCRIPTION ""
	::= { deviceEntry 10002 }
	
calcColourBrightness OBJECT-TYPE
	SYNTAX INTEGER (10..1000)
	ACCESS read-write
	STATUS mandatory
	DESCRIPTION ""
	::= { deviceEntry 10003 }

-------------------------
-- Traps ----------------
-------------------------

updateDpSwitch NOTIFICATION-TYPE
	OBJECTS { dpSwitch }
    STATUS current
    DESCRIPTION ""
	::= { dpUpdate 20 }

updateDpWorkmode NOTIFICATION-TYPE
	OBJECTS { dpWorkmode }
    STATUS current
    DESCRIPTION ""
	::= { dpUpdate 21 }

updateDpBright NOTIFICATION-TYPE
	OBJECTS { dpBright }
    STATUS current
    DESCRIPTION ""
	::= { dpUpdate 20 }

updateDpTemp NOTIFICATION-TYPE
	OBJECTS { dpTemp }
    STATUS current
    DESCRIPTION ""
	::= { dpUpdate 23 }

updateDpColour NOTIFICATION-TYPE
	OBJECTS { dpColour, calcColourHue, calcColourSaturation, calcColourBrightness }
    STATUS current
    DESCRIPTION ""
	::= { dpUpdate 24 }

END